env_params:
  gpus: 3
  accelerator: ddp
  accumulate_grad_batches: 1
  max_epochs: 1000
  log_every_n_steps: 50
  num_sanity_val_steps: 5
callback_params:
  modelCheckpoint:
    monitor: loss
    mode: min
    save_top_k: 1
    save_last: true
    filename: save_ckpt
  plug_in: null
base_params:
  dataloader: CPCDL
  dataloader_params:
    token_dict_path: /well/rahimi/users/sev854/project/HFValid/data/dict/dict4code
    age_dict_path: /well/rahimi/users/sev854/project/HFValid/data/dict/dict4age
    max_seq_length: 128
  model: CPC
  model_params:
    time_step: 10
    hidden_size: 256
    num_layer: 2
    hidden_dropout_prob: 0.2
    optimiser: sgd
    scheduler: {'T_max': 50, 'eta_min': 0.00003}
    optimiser_params: {'lr': 0.0001}
train_params:
  data_path: /well/rahimi/users/sev854/project/Mo/data/BEHRT.parquet
  batch_size: 64
  num_workers: 3
  shuffle: true
  mode: train
